# Generated by Django 4.2 on 2024-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prereservation',
            name='has_paid',
        ),
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('ready_for_reservation', '예약 준비 단계'), ('pre_reservation', '수요조사 모집 단계'), ('pre_reservation_complete', '수요조사 모집 완료'), ('reservation', '예약 모집 단계'), ('reservation_complete', '예약 모집 완료'), ('paused', '모집 일시중지 단계'), ('canceled', '대절 취소'), ('finished', '콘서트 완료')], default='ready_for_reservation', max_length=255),
        ),
    ]
