# Generated by Django 4.2 on 2024-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0002_remove_prereservation_has_paid_alter_concert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdiscount',
            name='sns_type',
            field=models.CharField(choices=[('twitter', '트위터'), ('instagram', '인스타')], default='twitter', max_length=255),
            preserve_default=False,
        ),
    ]
