# Generated by Django 4.2 on 2024-03-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0003_eventdiscount_sns_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('pre_reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_companions', to='handybusmvp.prereservation')),
            ],
        ),
    ]
