# Generated by Django 4.2 on 2024-03-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0004_surveycompanion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertRegionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('daegu', '대구'), ('daejeon', '대전'), ('busan', '부산'), ('changwon', '창원'), ('sejong', '세종'), ('cheongju', '청주')], max_length=255)),
                ('status', models.CharField(choices=[('before_confirmation', '대절 확정 전'), ('after_confirmation', '대절 확정 후'), ('closed', '마감'), ('cancelled', '무산')], default='before_confirmation', max_length=20)),
                ('open_chat_url', models.CharField(max_length=511)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handybusmvp.concert')),
            ],
        ),
        migrations.RemoveField(
            model_name='gatheringplace',
            name='reservation_fixed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('before_fixed', '대절 확정 전'), ('after_fixed', '대절 확정 후'), ('closed', '마감'), ('cancelled', '무산')], default='before_fixed', max_length=50),
        ),
        migrations.DeleteModel(
            name='OpenChatUrl',
        ),
    ]
