# Generated by Django 4.2 on 2024-03-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0005_concertregioninfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertregioninfo',
            name='stopover_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companion',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_companions', to='handybusmvp.reservation'),
        ),
        migrations.AlterField(
            model_name='concertregioninfo',
            name='region',
            field=models.CharField(choices=[('daegu', '대구'), ('daejeon', '대전'), ('busan', '부산'), ('changwon', '창원'), ('sejong', '세종'), ('cheongju', '청주'), ('cheonan', '천안')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eventdiscount',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handybusmvp.reservation'),
        ),
        migrations.AlterField(
            model_name='gatheringplace',
            name='region',
            field=models.CharField(choices=[('daegu', '대구'), ('daejeon', '대전'), ('busan', '부산'), ('changwon', '창원'), ('sejong', '세종'), ('cheongju', '청주'), ('cheonan', '천안')], max_length=255),
        ),
        migrations.AlterField(
            model_name='prereservation',
            name='region',
            field=models.CharField(choices=[('daegu', '대구'), ('daejeon', '대전'), ('busan', '부산'), ('changwon', '창원'), ('sejong', '세종'), ('cheongju', '청주'), ('cheonan', '천안')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='region',
            field=models.CharField(choices=[('daegu', '대구'), ('daejeon', '대전'), ('busan', '부산'), ('changwon', '창원'), ('sejong', '세종'), ('cheongju', '청주'), ('cheonan', '천안')], max_length=255),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('chat_link', models.CharField(max_length=511)),
                ('status', models.CharField(choices=[('before_confirmation', '대절 확정 전'), ('after_confirmation', '대절 확정 후'), ('closed', '마감'), ('cancelled', '무산')], default='before_confirmation', max_length=20)),
                ('concert_region_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handybusmvp.concertregioninfo')),
            ],
        ),
    ]
