# Generated by Django 4.2 on 2024-03-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0006_concertregioninfo_stopover_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertregioninfo',
            name='stopover_group',
        ),
    ]
