# Generated by Django 4.2 on 2024-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0007_remove_concertregioninfo_stopover_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertregioninfo',
            name='stopover_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
