# Generated by Django 4.2 on 2024-03-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0009_reservation_had_refunded_reservation_is_in_open_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='had_refunded',
            new_name='has_refunded',
        ),
    ]
