# Generated by Django 4.2 on 2024-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0010_rename_had_refunded_reservation_has_refunded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=255)),
                ('request_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
