# Generated by Django 4.2 on 2024-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handybusmvp', '0013_alter_concertregioninfo_open_chat_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='preferred_fallback_option',
        ),
        migrations.AddField(
            model_name='reservation',
            name='funnel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
